language: objective-c
osx_image: xcode8
cache:
  - cocoapods
  - bundler
before_install:
- brew update
- carthage bootstrap --verbose --platform iOS
install:
- gem install xcpretty
- gem install cocoapods --pre
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Slate'
script:
- pod update
- set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace ./Slate.xcworkspace -scheme Slate -destination 'platform=iOS Simulator,name=iPhone 6s' build test | xcpretty
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/689437210f0e8a62afde
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
Your unique webhook url for this service:
