language: objective-c
osx_image: xcode8
cache:
  - bundler
before_install:
- carthage bootstrap --verbose --platform iOS
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Slate'
script:
- env NSUnbufferedIO=YES xcodebuild -project ./Slate.xcodeproj -scheme Slate -destination 'platform=iOS Simulator,name=iPhone 6s' build test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/689437210f0e8a62afde
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
Your unique webhook url for this service:
