language: objective-c
osx_image: xcode8
cache:
  - bundler
  - Carthage
before_install:
- brew update
- travis_wait 30 (carthage_cache install -b slate-cache || (carthage bootstrap --platform iOS --no-use-binaries && carthage_cache publish -b slate-cache)) #--verbose
install:
- bundle
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Slate'
script:
- set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project ./Slate.xcodeproj -scheme Slate -destination 'platform=iOS Simulator,name=iPhone 6s' build test | xcpretty
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/689437210f0e8a62afde
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
